version: '3'
services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: ./prod.dockerfile
  #   restart: always
  #   ports:
  #     - 8080:80

  server:
    build:
      context: ./server
      dockerfile: ./prod.dockerfile
    restart: always
    env_file:
      - ./server/.env
    ports:
      - 4000:4000
